# Generated by Django 6.0.2 on 2026-04-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isActive',
        ),
    ]
