# Generated by Django 6.0.2 on 2026-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='freeUsageLimit',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='remainingFreeUsageCount',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usedFreeUsageCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
