# Generated by Django 6.0.2 on 2026-02-17 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offrereaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offrereaction',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='offers.offre'),
        ),
        migrations.AddConstraint(
            model_name='offrereaction',
            constraint=models.UniqueConstraint(fields=('agent', 'offre'), name='unique_agent_offre_reaction'),
        ),
    ]
