# Generated by Django 6.0.2 on 2026-05-07 11:19
#C:\Users\Lenovo\django_project\pfe_project2\pfe_project\interactions\migrations\0003_remove_offrereaction_unique_agent_offre_reaction_and_more.py
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
        ('offers', '0003_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offrereaction',
            name='unique_agent_offre_reaction',
        ),
        migrations.AlterField(
            model_name='offrereaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offrereaction',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offrereaction',
            name='proposedPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offrereaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='offrereaction',
            constraint=models.UniqueConstraint(fields=('agent', 'offre'), name='unique_agent_offer_reaction'),
        ),
    ]
