# Generated by Django 6.0.2 on 2026-03-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='offers/')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.offre')),
            ],
        ),
    ]
