# Generated by Django 6.0.2 on 2026-03-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='offreReaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='interactions.offrereaction'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=10),
        ),
    ]
