# Generated by Django 6.0.2 on 2026-05-12 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_offrereaction_alter_chat_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='agentArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='agentCustomTitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='chat',
            name='agentMuted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='blockedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='blockedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='clientArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='clientCustomTitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='chat',
            name='clientMuted',
            field=models.BooleanField(default=False),
        ),
    ]
