# Generated by Django 6.0.2 on 2026-04-30 10:36
#subscriptions\migrations\0002_plan_usagelimit_subscription_remainingusagecount_and_more.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='usageLimit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='remainingUsageCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='usageLimit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='usedUsageCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
