# Generated by Django 6.0.2 on 2026-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_usagelimit_subscription_remainingusagecount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='planType',
            field=models.CharField(choices=[('USAGE', 'Usage based'), ('DATE', 'Date based')], default='USAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='targetRole',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent')], default='CLIENT', max_length=20),
        ),
    ]
